# Generated by Django 2.2.7 on 2019-12-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edate', models.CharField(default=None, max_length=100)),
                ('enqid', models.IntegerField(default=0)),
                ('fname', models.CharField(default=None, max_length=50)),
                ('lname', models.CharField(default=None, max_length=50)),
                ('email', models.CharField(default=None, max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('Address', models.CharField(max_length=5000)),
                ('courses', models.CharField(default=None, max_length=50)),
                ('enquiry', models.CharField(default=None, max_length=70)),
                ('collagename', models.CharField(default=None, max_length=100)),
                ('stream', models.CharField(default=None, max_length=50)),
                ('year', models.CharField(default=None, max_length=50)),
                ('company', models.CharField(default=None, max_length=50)),
                ('designation', models.CharField(default=None, max_length=50)),
                ('year_exper', models.CharField(default=None, max_length=50)),
                ('weekday_date', models.CharField(default=None, max_length=50)),
                ('weekdays', models.CharField(default=None, max_length=50)),
                ('weekend_date', models.CharField(default=None, max_length=50)),
                ('weekend', models.CharField(default=None, max_length=50)),
                ('comments', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
