# Generated by Django 2.2.7 on 2020-02-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enq',
            name='status',
            field=models.CharField(default=None, max_length=70),
        ),
        migrations.AlterField(
            model_name='batch',
            name='sname',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='enq',
            name='year',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
    ]
