# Generated by Django 2.2.7 on 2020-02-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enq',
            name='reference_name',
            field=models.CharField(blank=True, default=None, max_length=70),
        ),
    ]
