# Generated by Django 2.2.7 on 2020-02-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enq',
            name='year',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
