# Generated by Django 2.2.7 on 2020-03-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmission',
            old_name='f_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='addmission',
            old_name='l_name',
            new_name='lname',
        ),
    ]
