# Generated by Django 2.2.7 on 2019-12-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edate', models.CharField(default=None, max_length=100)),
                ('fname', models.CharField(default=None, max_length=50)),
                ('lname', models.CharField(default=None, max_length=50)),
                ('email', models.CharField(default=None, max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('Address', models.CharField(max_length=5000)),
                ('courses', models.CharField(default=None, max_length=50)),
                ('tot_fees', models.CharField(max_length=50)),
                ('oneinstalldate', models.CharField(max_length=50)),
                ('oneinstallfees', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
