# Generated by Django 2.2.7 on 2019-12-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_addmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edate', models.CharField(default=None, max_length=100)),
                ('trainer', models.CharField(max_length=50)),
                ('courses', models.CharField(default=None, max_length=50)),
                ('batch_time', models.CharField(default=None, max_length=50)),
                ('batch_days', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
