# Generated by Django 2.2.7 on 2020-02-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200223_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enq',
            name='year',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
