# Generated by Django 2.2.7 on 2020-02-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200225_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edate', models.CharField(default=None, max_length=100)),
                ('enqalias', models.CharField(default=None, max_length=50)),
                ('enqid', models.IntegerField(default=0)),
                ('fname', models.CharField(default=None, max_length=50)),
                ('lname', models.CharField(default=None, max_length=50)),
                ('email', models.CharField(default=None, max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('Address', models.CharField(max_length=5000)),
                ('courses', models.CharField(default=None, max_length=50)),
                ('enquiry', models.CharField(default=None, max_length=70)),
                ('reference_name', models.CharField(blank=True, default=None, max_length=100)),
                ('status', models.CharField(default=None, max_length=70)),
                ('collagename', models.CharField(blank=True, default=None, max_length=100)),
                ('stream', models.CharField(blank=True, default=None, max_length=50)),
                ('year', models.CharField(blank=True, default='0', max_length=50)),
                ('company', models.CharField(blank=True, default=None, max_length=50)),
                ('designation', models.CharField(blank=True, default=None, max_length=50)),
                ('year_exper', models.CharField(blank=True, default=None, max_length=50)),
                ('Preferred_day', models.CharField(default=None, max_length=50)),
                ('weekday_date', models.CharField(blank=True, default=None, max_length=50)),
                ('weekdays_time', models.CharField(blank=True, default=None, max_length=50)),
                ('weekend_date', models.CharField(blank=True, default=None, max_length=50)),
                ('weekend_time', models.CharField(blank=True, default=None, max_length=50)),
                ('comments', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
