# Generated by Django 2.2.7 on 2020-02-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200212_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enq',
            name='reference_name',
            field=models.CharField(default=None, max_length=70, null=True),
        ),
    ]
