# Generated by Django 2.2.7 on 2020-02-27 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_modify'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modify',
        ),
    ]
